// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // CLI操作(migrate/db pull等)はSupabaseのTransaction poolerがintrospectionに対応しないため、
    // 直接接続用のDIRECT_URLを使う。アプリ実行時の接続先はPrismaClient生成時に別途指定する。
    url: process.env["DIRECT_URL"],
  },
});
